USE master 
GO

IF DB_ID('QLSACH') IS NOT NULL
DROP DATABASE QLSACH
GO

CREATE DATABASE QLSACH
GO

USE QLSACH
GO

CREATE TABLE SACH
(
	MASACH CHAR(4),
	TENSACH NCHAR(100),
	SOLUONG INT,
	DONGIA INT,
	MALOAI CHAR(2),
	KHTIEUBIEU INT

	CONSTRAINT PK_SACH
	PRIMARY KEY(MASACH)
)

CREATE TABLE KHACHHANG
(
	MALOAI CHAR(2),
	STT INT,
	HOTEN NCHAR(40),
	DIACHI NCHAR(100)

	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY(MALOAI, STT)
)

CREATE TABLE MUAHANG
(
	LOAIKH CHAR(2),
	SOTT INT,
	MASACH CHAR(4),
	NGAYMUA DATE,
	SOLUONG INT,
	DONGIA INT

	CONSTRAINT PK_MUAHANG
	PRIMARY KEY(LOAIKH, SOTT, MASACH)
)

ALTER TABLE SACH
ADD CONSTRAINT FK_SACH_KHACHHANG
	FOREIGN KEY(MALOAI, KHTIEUBIEU)
	REFERENCES KHACHHANG

ALTER TABLE MUAHANG
ADD CONSTRAINT FK_MUAHANG_SACH
	FOREIGN KEY(MASACH)
	REFERENCES SACH,

	CONSTRAINT FK_MUAHANG_KHACHHANG
	FOREIGN KEY(LOAIKH, SOTT)
	REFERENCES KHACHHANG

INSERT KHACHHANG(MALOAI, STT, HOTEN, DIACHI)
VALUES ('L1', 1, N'Nguyễn Thị Minh', N'123 Vuờn Lài, Tân Phú'),
	   ('L1', 2, N'Trần Trung Nghĩa', N'Phú Thọ Hòa, Tân Phú'),
	   ('L2', 1, N'Vũ Ánh Nguyệt', N'11 Võ Văn Ngân, Thủ Ðức')

INSERT SACH(MASACH, TENSACH, SOLUONG, DONGIA, MALOAI, KHTIEUBIEU)
VALUES ('S001', N'Ðồi Thỏ', 1000, 97000, 'L1', 1),
	   ('S002', N'Bài giảng cuối cùng', 24, 102000, 'L2', 1)

SET DATEFORMAT DMY
INSERT MUAHANG(LOAIKH, SOTT, MASACH, NGAYMUA, SOLUONG, DONGIA)
VALUES ('L1', 1, 'S001', '12-2-2009', 30, 90000),
	   ('L1', 2, 'S001', '30-12-2019', 20, 87000),
	   ('L2', 1, 'S002', '6-6-2019', 10, 100000),
	   ('L1', 2, 'S002', '7-3-2019', 5, 120000)

SELECT* FROM KHACHHANG
SELECT* FROM SACH
SELECT* FROM MUAHANG

--4 Cho biết danh sách khách hàng và tổng giá trị các hóa đơn đã mua
SELECT KH.*, SUM(MH.DONGIA) 'TONGGT'
FROM KHACHHANG KH JOIN MUAHANG MH
  ON KH.MALOAI = MH.LOAIKH AND KH.STT = MH.SOTT
GROUP BY KH.MALOAI, KH.STT, KH.HOTEN, KH.DIACHI

--5 Cho biết thông tin khách hàng họ Nguyễn có mua hàng trong tháng 12/2009 với số lượng > 10
SELECT KH.*, SUM(MH.SOLUONG) 'TONGSL'
FROM KHACHHANG KH JOIN MUAHANG MH
  ON KH.MALOAI = MH.LOAIKH AND KH.STT = MH.SOTT 
WHERE KH.HOTEN LIKE N'Nguyễn%'
  AND year(MH.NGAYMUA) = 2009 AND month(MH.NGAYMUA) = 12
  AND SOLUONG > 10
GROUP BY KH.MALOAI, KH.STT, KH.HOTEN, KH.DIACHI


