-- GHI CHÚ 1 DÒNG
/* GHI CHÚ NHIỀU DÒNG */

--PRINT DB_ID('QLDOIBONG')

USE master 
GO

--KIỂM TRA XEM CSDL ĐÃ TỒN TẠI HAY CHƯA
IF DB_ID('QLDOIBONG') IS NOT NULL --CSDL QLDOIBONG ĐÃ TỒN TẠI
	DROP DATABASE QLDOIBONG	--NẾU TỒN TẠI -> XÓA
GO --LỆNH GO -> CÂU LỆNH Ở TRÊN KẾT THÚC MỚI TIẾP TỤC

--TẠO CSDL QLDOIBONG
CREATE DATABASE QLDOIBONG
GO

--LỆNH USE ĐỂ TẠO BẢNG
USE QLDOIBONG
GO

CREATE TABLE DOI --KHÔNG PHÂN BIỆT CHỮ THƯỜNG VÀ HOA 
(
	--THUỘC TÍNH
	IDDOI INT,
	TENDOI NVARCHAR(50),
	DOITRUONG INT,
	SOLUONG INT

	--KHÓA CHÍNH
	CONSTRAINT PK_DOI	--ĐẶT TÊN CHO KHÓA CHÍNH
	PRIMARY KEY(IDDOI)	--TẠO KHÓA CHÍNH
)

CREATE TABLE BOTRI
(
	IDDOI INT,
	IDTHANHVIEN INT,
	DIACHI NVARCHAR(100),
	NHIEMVU NVARCHAR(100),
	QUANLI INT

	CONSTRAINT PK_BOTRI
	PRIMARY KEY (IDDOI,IDTHANHVIEN)
)

CREATE TABLE THANHVIEN
(
	IDTHANHVIEN INT,
	HOTEN NVARCHAR(50),
	SOCMND CHAR(9),
	DIACHI NVARCHAR(50),
	NGAYSINH DATE

	CONSTRAINT PK_THANHVIEN
	PRIMARY KEY (IDTHANHVIEN)
)

--TẠO KHÓA NGOẠI VÀ DÂY LIÊN KẾT
--SỬA LẠI BẢNG
ALTER TABLE BOTRI
ADD
	CONSTRAINT FK_BOTRI_DOI --ĐẶT TÊN KHÓA NGOẠI
	FOREIGN KEY (IDDOI) --KHAI BÁO KHÓA NGOẠI
	REFERENCES DOI, --TẠO DÂY LIÊN KẾT

	CONSTRAINT FK_BOTRI_THANHVIEN_TV
	FOREIGN KEY (IDTHANHVIEN)
	REFERENCES THANHVIEN,

	CONSTRAINT FK_BOTRI_THANHVIEN_QL
	FOREIGN KEY (QUANLI)
	REFERENCES THANHVIEN

ALTER TABLE DOI
ADD
	CONSTRAINT FK_DOI_THANHVIEN
	FOREIGN KEY (DOITRUONG)
	REFERENCES THANHVIEN

--NHẬP LIỆU
INSERT DOI(IDDOI,TENDOI)
VALUES	(2, N'ĐỘI TÂN PHÚ'),
		(7, N'ĐỘI BÌNH PHÚ')

SELECT * --LẤY TOÀN BỘ THUỘC TÍNH
FROM DOI

SET DATEFORMAT DMY -- ĐỔI ĐỊNH DẠNG NGÀY/THÁNG/NĂM
GO

INSERT THANHVIEN(IDTHANHVIEN,HOTEN,SOCMND,DIACHI,NGAYSINH)
VALUES	(1, N'Nguyễn Quan Tùng', '240674018', N'TPHCM', '30/1/2000'),
		(2, N'Lưu Phi Nam', '240674027', N'Quảng Nam', '12/3/2001'),
		(3, N'Lê Quang Bảo', '240674063', N'Quảng Ngãi', '14/5/1999'),
		(4, N'Hà Ngọc Thúy', '240674504', N'TPHCM', '26/7/1998'),
		(5, N'Trương Thị Minh', '240674405', N'Hà Nội', null),
		(6, N'Ngô Thị Thủy', '240674306', null, '18/9/2000')

SELECT *
FROM THANHVIEN

--CẬP NHẬT LẠI DỮ LIỆU
UPDATE DOI
SET DOITRUONG = 1, SOLUONG = 11
WHERE IDDOI = 2 --TÌM DÒNG CẦN CẬP NHẬT

UPDATE DOI
SET DOITRUONG = 5
WHERE IDDOI = 7

SELECT * FROM DOI