version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: demodb
      MYSQL_USER: htthanh
      MYSQL_PASSWORD: thanh123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
