USE master
GO

IF DB_ID('QLPHONGTHI') IS NOT NULL
	DROP DATABASE QLPHONGTHI
GO

CREATE DATABASE QLPHONGTHI
GO

USE QLPHONGTHI
GO

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(5),
	TENGV NCHAR(40),
	DIACHI NCHAR(100),
	VAITRO NCHAR(40)

	CONSTRAINT PK_GIAOVIEN
	PRIMARY KEY(MAGV)
)

CREATE TABLE THISINH
(
	SBD CHAR(4),
	DIEMTHI CHAR(3),
	HOTEN NCHAR(40),
	DIACHI NCHAR(100),
	NGAYSINH DATE,
	PHONGTHI CHAR(4)

	CONSTRAINT PK_THISINH
	PRIMARY KEY(SBD)
)

CREATE TABLE PHONGTHI
(
	IDPHONG CHAR(4),
	IDDIEMTHI CHAR(3),
	CANBO CHAR(5),
	SOBAN INT,
	THIETBI NCHAR(40)

	CONSTRAINT PK_PHONGTHI
	PRIMARY KEY(IDPHONG, IDDIEMTHI)
)

ALTER TABLE PHONGTHI
ADD CONSTRAINT FK_PHONGTHI_CANBO
	FOREIGN KEY(CANBO)
	REFERENCES GIAOVIEN

ALTER TABLE THISINH
ADD CONSTRAINT FK_THISINH_PHONGTHI
	FOREIGN KEY(PHONGTHI, DIEMTHI)
	REFERENCES PHONGTHI

INSERT GIAOVIEN(MAGV, TENGV, DIACHI, VAITRO)
VALUES ('GV001', N'Trần Thị Bé',		N'Nguyễn Xí Q.Bình Thạnh',	N'Cán bộ'),
	   ('GV002', N'Nguyễn Minh Tâm',	N'2 Trần Hưng Ðạo Q5',		N'Giám sát'),
	   ('GV003', N'Trần Van Li',		N'30 Hà Tồn Quyền Q5',		N'Cán bộ')

INSERT PHONGTHI(IDPHONG, IDDIEMTHI, CANBO, SOBAN, THIETBI)
VALUES ('P001', 'DD1', 'GV001', 25, N'Mic – Loa – Tivi'),
	   ('P002', 'DD1', 'GV002', 30, N'Mic – Loa – Tivi'),
	   ('P001', 'DD2', 'GV003', 15, NULL)

SET DATEFORMAT DMY
INSERT THISINH(SBD, DIEMTHI, HOTEN, DIACHI, NGAYSINH, PHONGTHI)
VALUES ('0231', 'DD1', N'Nguyễn Quan Tùng', N'TPHCM', '30/11/2000', 'P001'),
	   ('0230', 'DD2', N'Lưu Phi Nam', N'Hải Phòng', '12/2/2000', 'P001'),
	   ('0234', 'DD1', N'Lê Quang Bảo', N'Hà Nội', '13/2/2000', 'P002'),
	   ('0233', 'DD2', N'Hà Ngọc Thúy', N'TPHCM', '24/4/2000', 'P001')

SELECT* FROM GIAOVIEN
SELECT* FROM THISINH
SELECT* FROM PHONGTHI

--4. Cho biết ID phòng thi, tên cán bộ và số lượng thí sinh của phòng đó
SELECT PT.IDPHONG, GV.TENGV, PT.SOBAN
FROM PHONGTHI PT JOIN GIAOVIEN GV
  ON PT.CANBO = GV.MAGV 

--5. Cho biết danh sách phòng thi, tên cán bộ giám sát của phòng có trên 15
--	 bàn có thí sinh ở Hải Phòng thi. 
SELECT PT.*, GV.TENGV
FROM PHONGTHI PT JOIN GIAOVIEN GV 
  ON PT.CANBO = GV.MAGV JOIN THISINH TS
  ON TS.DIEMTHI = PT.IDDIEMTHI AND TS.PHONGTHI = PT.IDPHONG
WHERE PT.SOBAN > 15 
  AND TS.DIACHI= N'Hải Phòng'
  AND GV.VAITRO = N'Giám sát'